# Generated by Django 4.1.6 on 2023-02-16 18:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("rating", models.FloatField()),
                ("current_episode", models.IntegerField()),
                ("watched", models.BooleanField(default=False)),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="series", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("rating", models.FloatField()),
                ("watched", models.BooleanField(default=False)),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="movies", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
