# Generated by Django 4.1.6 on 2023-02-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gui", "0002_remove_movie_watched_remove_series_current_episode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="watched",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="series",
            name="watched",
            field=models.BooleanField(default=False),
        ),
    ]
