# Generated by Django 4.1.6 on 2023-02-17 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gui", "0004_remove_movie_users_remove_movie_watched_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="movies_plan_to_watch",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="movies_watched",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="series_plan_to_watch",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="series_watched",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="added_by",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="description",
        ),
        migrations.AlterField(
            model_name="movie",
            name="rating",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="movie",
            name="year",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="Series",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
        migrations.AddField(
            model_name="movie",
            name="movie_list",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gui.movielist",
            ),
        ),
    ]
