# Generated by Django 4.1.6 on 2023-02-17 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gui", "0005_movielist_remove_userprofile_movies_plan_to_watch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movielist",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
