# Generated by Django 4.1.6 on 2023-02-17 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gui", "0006_movielist_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(default="No description available")),
                ("rating", models.DecimalField(decimal_places=1, max_digits=3)),
                (
                    "year_release",
                    models.PositiveSmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "year_completion",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("O", "On going"), ("C", "Completed")],
                        default="Completed",
                        max_length=1,
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="movie",
            name="movie_list",
        ),
        migrations.AddField(
            model_name="movie",
            name="added_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="description",
            field=models.TextField(default="No description available"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="rating",
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="movie",
            name="year",
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name="MovieList",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="movies_plan_to_watch",
            field=models.ManyToManyField(
                related_name="plan_to_watch_by", to="gui.movie"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="movies_watched",
            field=models.ManyToManyField(related_name="watched_by", to="gui.movie"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="series_plan_to_watch",
            field=models.ManyToManyField(
                related_name="plan_to_watch_by", to="gui.series"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="series_watched",
            field=models.ManyToManyField(related_name="watched_by", to="gui.series"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
